apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: voting-app 
spec:
  selector:
    name: redis-pod
    app: voting-app
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379